# Generated by Django 4.1.4 on 2023-06-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='productimg')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bahawalpur', 'Bahawalpur'), ('Bahawalnagar', 'Bahawalnagar'), ('Rahim Yar Khan', 'Rahim Yar Khan'), ('Gujranwala', 'Gujranwala'), ('Gujrat', 'Gujrat'), ('Sargodha', 'Sargodha'), ('Khushab', 'Khushab'), ('Mianwali', 'Mianwali'), ('Bhakkar', 'Bhakkar'), ('Sahiwal', 'Sahiwal'), ('Pakpattan', 'Pakpattan'), ('Okara', 'Okara')], max_length=250),
        ),
    ]
